apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-server
    spec:
      containers:
        - name: server
          image: ghcr.io/pascariucosmin93/imchi/immich-server:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 2283
          envFrom:
            - configMapRef:
                name: immich-config
            - secretRef:
                name: immich-secrets
          readinessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 90
            periodSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 4Gi
          volumeMounts:
            - name: library
              mountPath: /data
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
