apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  annotations:
    io.cilium/lb-ipam-ips: 10.10.2.55
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: immich-server
  ports:
    - name: http
      port: 80
      targetPort: http
